### ISSUE TITLE
cost733class Support ifort

### ISSUE THREAD

**Issue by Hallofanf** [lochbika/cost733class#1]
Hi, thank you for your work, it really useful for me as COST733CLASS not update any more.
But I have a question, does it support compiler "ifort" in this version?  I am much familiar with ifort, and i don't know about cmake.

**Comment by lochbika** [comment]
Hi Hollofanf,
it is certainly possible to (try to) compile it with the ifort compiler. Unfortunately, I do not have access to the intel compilers, so I can't test it. However, I think it should be fairly easy to add the support for ifort, since it would only require some changes in the top-level CMakeLists.txt file.
If you don't want to/can't edit this file you can also modify the compiler selection with the interactive tool ccmake. Just create a new build directory and run ccmake within it.
Hope this helps

**Comment by Hallofanf** [comment]
Hi lochbika:
     Thank you for your reply, I wil try it.
