### ISSUE TITLE
Created a conda-forge recipe to be published

### ISSUE THREAD

**Issue by cofinoa** [lochbika/cost733class#2]
Dear @lochbika , 

I have created a conda-forge recipe for the cost733class software, based using your repo as source:
https://github.com/conda-forge/staged-recipes/pull/22930

you can take a look, in particular to the about section:
https://github.com/conda-forge/staged-recipes/pull/22930/files#diff-491c13fe4c0b19eccec1cbff47d944a0054ef87c090b3d50d600a2676a49e6c3R49-R59

Any feedback is more than welcome, in particular let me know if you are interested to be added as maintainer.

Regards

**Comment by lochbika** [comment]
Hi @cofinoa 
this is great, go ahead! I'm very pleased to see that cost733class makes it so far and that it's been kept alive and usable.
I was not aware that there is still a (scientific) community around it, and actually using it. Maybe it could be worth a mention in the Readme.md?! I certainly will update the file when the conda package is online.

Since you are the initiator of the conda-forge package, I think it is best that you are the main maintainer for that. I will be here to maintain the github repo. But, I really would like to see users to pass their feedback, or even code improvements to this repository in the form of issues, pull requests, or even just mail to me.

Your activity is very much appreciated!

Best

**Comment by cofinoa** [comment]
@lochbika FYI

The `cost733class` recipe is already published in conda-forge and availiable:
https://anaconda.org/conda-forge/cost733class

Thx!
